services:
  - type: web
    name: gestion-restaurant
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Gestion Restaurant"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:Kmpsn/3nTpZoZ5lahgpPdnlKmT5tiUjZVI1lXFEiSY8=
      - key: APP_URL
        fromService:
          type: web
          property: url
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: mysql
          property: host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: restaurant
      - key: DB_USERNAME
        fromService:
          type: mysql
          property: username
      - key: DB_PASSWORD
        fromService:
          type: mysql
          property: password

  - type: mysql
    name: gestion-restaurant-db
    plan: free
    region: frankfurt
    ipWhitelist: []
    databaseName: restaurant
    user: admin
